### ISSUE TITLE
Flow checking uninitialized files

### ISSUE THREAD

**Issue by chrisblossom** [dsilva/webstorm-plugin-flow-typecheck#4]
I am getting flow errors in files that are not initiated with `/* @flow */`. Is this the expected behavior? If so, is it possible to only enable this plugin when flow is initialized?

**Comment by dsilva** [comment]
I can change it so the plugin only runs for files that flow would normally check (with the @flow marker).

On the other hand, are the errors helpful?  Are they real type mismatches that lead to problems at runtime?

**Comment by chrisblossom** [comment]
I do not find them helpful because flow is designed to only run in files that have flow enabled so you can opt in to type checking / add flowtype to an existing project. It is similar if there were Typescript checks on .js files.

The only way I can see it being helpful is the following scenario:

``` js
// flow_typed.js

/* @flow */

const returnMessage = (message: string) => message;

export default returnMessage;
```

``` js
// not_flow_typed.js

import returnMessage from './flow_typed.js';

// should ignore the following code
const badType = '1' + 1; // returns "11"

// Origional JS code that should be fixed when flow is added to file
if (badType === '11') {
  // do something expected here
}

const message = returnMessage(12345); // throw flow type error
```

Flow itself does not do that though. I actually use [gcanti/babel-plugin-tcomb](https://github.com/gcanti/babel-plugin-tcomb) in development for runtime exception errors to catch such problems.

Does that make sense?

**Comment by dsilva** [comment]
Makes sense.  I'll skip files that flow itself would also skip.

**Comment by dsilva** [comment]
released https://github.com/dsilva/webstorm-plugin-flow-typecheck/releases/tag/1.2.3

**Comment by chrisblossom** [comment]
Thank you! I'll give it a try tomorrow.

**Comment by chrisblossom** [comment]
Works great! Thanks again!
