### ISSUE TITLE
2016.3 EAP has flow support

### ISSUE THREAD

**Issue by vonovak** [dsilva/webstorm-plugin-flow-typecheck#7]
just a heads up, feel free to close this
[source](https://blog.jetbrains.com/webstorm/2016/08/webstorm-2016-3-early-access-preview/#flow)

**Comment by dsilva** [comment]
Thank you for letting me know -- that's excellent news :)

**Comment by vonovak** [comment]
@dsilva thanks for the plugin, it was very helpful!

**Comment by chrisblossom** [comment]
I would like to say thank you as well. You've been very helpful and this plugin helped me pick Flow over TS (was the last thing missing in my workflow).
