### ISSUE TITLE
What about IntelliJ

### ISSUE THREAD

**Issue by khanetor** [dsilva/webstorm-plugin-flow-typecheck#8]
Even though WebStorm has built-in Flow support, this feature is still missing in IntelliJ (or I do not know how to enable it). The only thing I can find in IntelliJ is to enable Flow syntax. Should I still use this if I am on IntelliJ?

**Comment by dsilva** [comment]
You can, but you should also ask JetBrains if they plan on porting their Flow support from WebStorm to IntelliJ.

**Comment by cem2ran** [comment]
@nlhkh Flow support is now generally available with 2016.3:
https://blog.jetbrains.com/idea/2016/11/intellij-idea-2016-3-ga-java-8-and-es6-debugger-and-ui-improvements-and-a-ton-more

**Comment by khanetor** [comment]
Wow this was quick!

**Comment by cem2ran** [comment]
It has been there for a while under the Early Access Preview (EAP) releases.

**Comment by dsilva** [comment]
Great!
